package org.example.cayenne.persistent.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.example.cayenne.persistent.Employee;

/**
 * Class _Department was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Department extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "ID";

    public static final StringProperty<String> LOCATION = PropertyFactory.createString("location", String.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final ListProperty<Employee> DEPARTMENTEMPLOYEE = PropertyFactory.createList("departmentemployee", Employee.class);

    protected String location;
    protected String name;

    protected Object departmentemployee;

    public void setLocation(String location) {
        beforePropertyWrite("location", this.location, location);
        this.location = location;
    }

    public String getLocation() {
        beforePropertyRead("location");
        return this.location;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void addToDepartmentemployee(Employee obj) {
        addToManyTarget("departmentemployee", obj, true);
    }

    public void removeFromDepartmentemployee(Employee obj) {
        removeToManyTarget("departmentemployee", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Employee> getDepartmentemployee() {
        return (List<Employee>)readProperty("departmentemployee");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "location":
                return this.location;
            case "name":
                return this.name;
            case "departmentemployee":
                return this.departmentemployee;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "location":
                this.location = (String)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "departmentemployee":
                this.departmentemployee = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.location);
        out.writeObject(this.name);
        out.writeObject(this.departmentemployee);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.location = (String)in.readObject();
        this.name = (String)in.readObject();
        this.departmentemployee = in.readObject();
    }

}
